import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AdminHeader from "@/components/layout/AdminHeader";
import { ToastProvider } from "@/components/common/ToastProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Toeic Prep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <AdminHeader />
          <main className="h-[calc(100vh-64px)] overflow-y-auto">{children}</main>
        </ToastProvider>
      </body>
    </html>
  );
}
